# Permalinks
permalink: pretty

# Compile CSS
sass:
  style: compressed
sass:
  sass_dir: _sass

# Setup
title:            Assembly Design Language
tagline:          'Quizlet Design System'
url:              https://assembly.quizlet.design
baseurl:          /assembly-design-language/
